"""GitHub integration for AutoCoder"""
import base64
import urllib.request
import json

class GitHubPusher:
    def __init__(self, github_token: str):
        self.token = github_token
        self.api_base = "https://api.github.com"

    def push_project(self, repo_name: str, files: list, description: str = "") -> dict:
        """Create a repo and push all files."""
        # Create repo if not exists
        self._create_repo(repo_name, description)

        # Push each file
        for f in files:
            self._push_file(repo_name, f["name"], f["content"], f.get("message", f"Add {f['name']}"))

        return {"url": f"https://github.com/{repo_name}", "files_pushed": len(files)}

    def _create_repo(self, repo_name: str, description: str) -> None:
        """Create GitHub repo if not exists."""
        owner, name = repo_name.split("/", 1)
        payload = json.dumps({
            "name": name,
            "description": description or "Generated by AutoCoder",
            "private": False,
            "auto_init": True
        }).encode()

        req = urllib.request.Request(
            f"{self.api_base}/repos/{owner}/{name}",
            data=payload,
            method="GET"
        )
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Accept", "application/vnd.github+json")

        # Check if exists
        try:
            resp = urllib.request.urlopen(req, timeout=10)
            # Repo exists
            return
        except urllib.error.HTTPError as e:
            if e.code != 404:
                return

        # Create repo
        payload = json.dumps({
            "name": name,
            "description": description or "Generated by AutoCoder",
            "private": False
        }).encode()

        req = urllib.request.Request(
            f"{self.api_base}/user/repos",
            data=payload,
            method="POST"
        )
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Content-Type", "application/vnd.github+json")

        try:
            urllib.request.urlopen(req, timeout=10)
        except:
            pass

    def _push_file(self, repo_name: str, path: str, content: str, message: str) -> None:
        """Push a single file to GitHub."""
        owner, name = repo_name.split("/", 1)
        content_b64 = base64.b64encode(content.encode("utf-8")).decode("utf-8")

        payload = json.dumps({
            "message": message,
            "content": content_b64
        }).encode()

        # Get current SHA if file exists
        req = urllib.request.Request(
            f"{self.api_base}/repos/{owner}/{name}/contents/{path}",
            method="GET"
        )
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Accept", "application/vnd.github+json")

        sha = None
        try:
            resp = urllib.request.urlopen(req, timeout=10)
            data = json.loads(resp.read())
            sha = data.get("sha")
        except:
            pass

        if sha:
            payload = json.dumps({"message": message, "content": content_b64, "sha": sha}).encode()

        req = urllib.request.Request(
            f"{self.api_base}/repos/{owner}/{name}/contents/{path}",
            data=payload,
            method="PUT"
        )
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Content-Type", "application/vnd.github+json")

        try:
            urllib.request.urlopen(req, timeout=10)
        except Exception as e:
            print(f"Failed to push {path}: {e}")
